#!/usr/bin/env bash
#
# Generates `.env.custom` from the version-controlled `deploy/env.base`,
# plus secrets that must never be committed.
#
# Idempotent: existing secrets in `.env.custom` are preserved, not regenerated.
# Run this BEFORE ./install.sh, and again after pulling a new env.base.
#
set -euo pipefail

cd "$(dirname "$0")/.."

BASE="deploy/env.base"
TARGET=".env.custom"

[[ -f "$BASE" ]] || { echo "FAIL: $BASE missing"; exit 1; }

# Generate a secret only if we do not already have one.
# Existing value is read out of the current .env.custom, never printed.
existing_secret=""
if [[ -f "$TARGET" ]]; then
  existing_secret="$(grep -E '^LAUNCHPAD_RPC_SHARED_SECRET=' "$TARGET" | tail -1 | cut -d= -f2- || true)"
fi

if [[ -n "$existing_secret" ]]; then
  echo "LAUNCHPAD_RPC_SHARED_SECRET: reusing existing value."
  secret="$existing_secret"
else
  echo "LAUNCHPAD_RPC_SHARED_SECRET: generating new value."
  secret="$(LC_ALL=C head -c 512 /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 50)"
fi

# Back up an existing .env.custom before replacing it.
if [[ -f "$TARGET" ]]; then
  cp "$TARGET" "${TARGET}.bak"
  echo "Previous $TARGET saved as ${TARGET}.bak"
fi

{
  echo "# GENERATED by deploy/bootstrap.sh -- DO NOT COMMIT. DO NOT EDIT BY HAND."
  echo "# Edit deploy/env.base for config, then re-run deploy/bootstrap.sh."
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  cat "$BASE"
  echo
  echo "# --- generated secrets (never committed) ---"
  echo "LAUNCHPAD_RPC_SHARED_SECRET=${secret}"
} > "$TARGET"

chmod 600 "$TARGET"

echo "Wrote $TARGET (mode 600)."
echo "Non-secret settings now in effect:"
grep -E '^(SENTRY_EVENT_RETENTION_DAYS|SENTRY_BIND|COMPOSE_PROFILES|COMPOSE_PROJECT_NAME|SENTRY_TASKWORKER_CONCURRENCY)=' "$TARGET"
echo
echo "Next: ./install.sh"
